# Generated by Django 3.0.7 on 2021-04-15 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup', models.CharField(default='', max_length=100)),
                ('field_of_internship', models.CharField(default='', max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('stipend', models.CharField(max_length=100)),
                ('skills_required', models.CharField(max_length=500)),
                ('no_of_internships', models.PositiveIntegerField()),
                ('perks', models.CharField(max_length=100)),
                ('apply_by', models.DateField(default='2000-01-01', help_text='YYYY-MM-DD Format should be followed for the date.')),
                ('who_should_apply', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', max_length=1200)),
                ('resume', models.URLField(default='', help_text='Add the drive link to your resume.')),
                ('internship', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='home.Internship')),
            ],
        ),
    ]
