# Generated by Django 3.0.7 on 2021-04-17 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='startup',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='message',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='resume',
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='applied_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='intern', to=settings.AUTH_USER_MODEL),
        ),
    ]
