# Generated by Django 3.0.7 on 2021-04-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210417_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='company_logo',
            field=models.ImageField(default='logo/download.png', upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='internship',
            name='start_by',
            field=models.DateField(default='2000-01-01', help_text='YYYY-MM-DD Format should be followed for the date.'),
        ),
    ]
