# Generated by Django 3.2 on 2021-04-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210417_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='internship',
            name='domain',
            field=models.ManyToManyField(to='home.Domains'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='domain',
            field=models.ManyToManyField(to='home.Domains'),
        ),
    ]
