# Generated by Django 3.0.7 on 2021-04-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210419_0357'),
        ('home', '0003_auto_20210418_1135'),
    ]

    operations = [
    ]
