# Generated by Django 3.0.7 on 2021-04-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20210420_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='message',
            field=models.TextField(blank=True, default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='resume',
            field=models.URLField(default='', help_text='Add the drive link to your resume.'),
        ),
        migrations.RemoveField(
            model_name='internship',
            name='domain',
        ),
        migrations.AddField(
            model_name='internship',
            name='domain',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='domain',
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='domain',
            field=models.BooleanField(default=True),
        ),
    ]
