# Generated by Django 3.0.7 on 2021-04-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210421_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='message',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='domain',
        ),
        migrations.AddField(
            model_name='internship',
            name='domain',
            field=models.ManyToManyField(to='home.Domains'),
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='domain',
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='domain',
            field=models.ManyToManyField(to='home.Domains'),
        ),
    ]
