# Generated by Django 3.0.7 on 2021-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_internship_is_meet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='field_of_internship',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='perks',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='skills_required',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='who_should_apply',
        ),
        migrations.AlterField(
            model_name='internship',
            name='apply_by',
            field=models.DateField(default='2021-04-25 16:30:00', help_text='YYYY-MM-DD Format should be followed for the date.'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='meet_link',
            field=models.URLField(blank=True, default='', help_text='Add the drive link to your resume.'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='start_by',
            field=models.DateTimeField(default='2000-01-01', help_text='YYYY-MM-DD Format should be followed for the date.'),
        ),
    ]
