# Generated by Django 3.0.7 on 2021-04-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210423_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='apply_by',
            field=models.DateTimeField(default='2021-04-25 16:30:00', help_text='YYYY-MM-DD Format should be followed for the date.'),
        ),
    ]
