# Generated by Django 3.0.7 on 2021-04-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210423_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='no_of_internships',
            field=models.CharField(max_length=100),
        ),
    ]
