# Generated by Django 3.0.7 on 2021-04-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.URLField(default='', help_text='Add the drive link to your resume.'),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
