# Generated by Django 3.0.7 on 2021-04-17 11:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210417_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+919999999999', max_length=128, region=None),
        ),
    ]
