# Generated by Django 3.0.7 on 2021-04-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resume',
        ),
    ]
