# Generated by Django 3.0.7 on 2021-04-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210420_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
